baseurl = "https://theoldevangelization.com/"
languageCode = "en-us"
title = "The Old Evangelization"

theme = "casper"
canonifyurls = true

[params]
#  description = "Hard Truths for Hard Times"
  cover = "images/cover.jpg"
  author = "P.F. Hawkins"
#  authorlocation = "Michigan, U.S.A."
#  authorwebsite = "http://vjeantet.fr"
#  bio= "my bio"
#  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-40425246-1"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
#   RSSLink = "http://feeds.feedburner.com/..."
#  githubName = "pfhawkins"
#  twitterName = "evangelizare"
#  facebookName = "TheOldEvangelization"
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  [params.social]
    twitter = "evangelizare"


[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about"

[[menu.main]]
  name = "Blogroll"
  identifier = "blogroll"
  url = "/blogroll"

[[menu.main]]
  name = "Contact"
  identifier = "contact"
  url = "/contact"
