title = "The Old Evangelization"
baseURL = "https://theoldevangelization.com"
languageCode = "en-us"
theme = "ananke"
themesDir = "./themes"

#MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
#SectionPagesMenu = "main"
Paginate = 9 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-40425246-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Catholicism and Evangelization, Explained"
  facebook = "https://www.facebook.com/TheOldEvangelization/"
  twitter = "https://twitter.com/evangelizare"
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/nucover.jpg"
  recent_posts_number = 7

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about"

[[menu.main]]
  name = "Blogroll"
  identifier = "blogroll"
  url = "/blogroll"

[[menu.main]]
  name = "Contact"
  identifier = "contact"
  url = "/contact"

[[menu.main]]
  name = "Pascendi/Modernism"
  identifier = "pascendi"
  url = "/pascendi-series"
